### ISSUE TITLE
select support

### ISSUE THREAD

**Issue by akin520** [clia/rcproxy#3]
Is there a way to add support for the select

**Comment by clia** [comment]
According to Redis [official document](https://redis.io/commands/select/)

> When using Redis Cluster, the SELECT command cannot be used, since Redis Cluster only supports database zero. In the case of a Redis Cluster, having multiple databases would be useless and an unnecessary source of complexity. Commands operating atomically on a single database would not be possible with the Redis Cluster design and goals.
